<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Modules\Setting\Models\Setting;

class SettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // General Settings
            [
                'key' => 'app_name',
                'value' => config('app.name', 'LaraKit'),
                'type' => 'string',
                'group' => 'general',
                'label' => 'Application Name',
                'description' => 'The name of your application',
                'order' => 1,
            ],
            [
                'key' => 'app_tagline',
                'value' => 'Modern Web Application',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Tagline',
                'description' => 'A short tagline for your site',
                'order' => 2,
            ],
            [
                'key' => 'app_description',
                'value' => 'A powerful and modern web application built with Laravel',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Description',
                'description' => 'Brief description of your application',
                'order' => 3,
            ],
            [
                'key' => 'footer_text',
                'value' => 'Building the future, one line of code at a time',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Footer Text',
                'description' => 'Text displayed in the footer',
                'order' => 4,
            ],
            [
                'key' => 'copyright_text',
                'value' => '© ' . date('Y') . ' LaraKit. All rights reserved.',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Copyright Text',
                'description' => 'Copyright notice',
                'order' => 5,
            ],
            [
                'key' => 'contact_email',
                'value' => 'contact@larakit.com',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Contact Email',
                'description' => 'Primary contact email address',
                'order' => 6,
            ],
            [
                'key' => 'contact_phone',
                'value' => '+1 234 567 8900',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Contact Phone',
                'description' => 'Primary contact phone number',
                'order' => 7,
            ],
            [
                'key' => 'address',
                'value' => '123 Business Street, City, State 12345',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Address',
                'description' => 'Physical address',
                'order' => 8,
            ],
            [
                'key' => 'timezone',
                'value' => 'UTC',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Timezone',
                'description' => 'Application timezone',
                'order' => 9,
            ],
            [
                'key' => 'date_format',
                'value' => 'Y-m-d',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Date Format',
                'description' => 'Default date format',
                'order' => 10,
            ],
            [
                'key' => 'time_format',
                'value' => 'H:i:s',
                'type' => 'string',
                'group' => 'general',
                'label' => 'Time Format',
                'description' => 'Default time format',
                'order' => 11,
            ],

            // SEO Settings
            [
                'key' => 'meta_title',
                'value' => 'LaraKit - Modern Web Application',
                'type' => 'string',
                'group' => 'seo',
                'label' => 'Meta Title',
                'description' => 'Default page title for SEO',
                'order' => 1,
            ],
            [
                'key' => 'meta_description',
                'value' => 'A powerful and modern web application built with Laravel framework',
                'type' => 'string',
                'group' => 'seo',
                'label' => 'Meta Description',
                'description' => 'Default meta description',
                'order' => 2,
            ],
            [
                'key' => 'meta_keywords',
                'value' => 'laravel, web application, modern, php',
                'type' => 'string',
                'group' => 'seo',
                'label' => 'Meta Keywords',
                'description' => 'Comma-separated keywords',
                'order' => 3,
            ],
            [
                'key' => 'og_title',
                'value' => 'LaraKit - Modern Web Application',
                'type' => 'string',
                'group' => 'seo',
                'label' => 'Open Graph Title',
                'description' => 'Title for social media sharing',
                'order' => 4,
            ],
            [
                'key' => 'og_description',
                'value' => 'A powerful and modern web application built with Laravel',
                'type' => 'string',
                'group' => 'seo',
                'label' => 'Open Graph Description',
                'description' => 'Description for social media sharing',
                'order' => 5,
            ],
            [
                'key' => 'twitter_card',
                'value' => 'summary_large_image',
                'type' => 'string',
                'group' => 'seo',
                'label' => 'Twitter Card Type',
                'description' => 'Twitter card type for social sharing',
                'order' => 6,
            ],
            [
                'key' => 'google_analytics_id',
                'value' => '',
                'type' => 'string',
                'group' => 'seo',
                'label' => 'Google Analytics ID',
                'description' => 'Google Analytics tracking ID',
                'order' => 7,
            ],

            // Auth & Security Settings
            [
                'key' => 'allow_registration',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'auth',
                'label' => 'Allow User Registration',
                'description' => 'Enable or disable user registration',
                'order' => 1,
            ],
            [
                'key' => 'require_email_verification',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'auth',
                'label' => 'Require Email Verification',
                'description' => 'Users must verify email before login',
                'order' => 2,
            ],
            [
                'key' => 'require_mobile_verification',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'auth',
                'label' => 'Require Mobile Verification',
                'description' => 'Users must verify mobile number',
                'order' => 3,
            ],
            [
                'key' => 'enable_2fa',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'auth',
                'label' => 'Enable Two-Factor Authentication',
                'description' => 'Enable 2FA for enhanced security',
                'order' => 4,
            ],
            [
                'key' => 'session_lifetime',
                'value' => '120',
                'type' => 'integer',
                'group' => 'auth',
                'label' => 'Session Lifetime (minutes)',
                'description' => 'Session timeout duration in minutes',
                'order' => 5,
            ],
            [
                'key' => 'password_min_length',
                'value' => '8',
                'type' => 'integer',
                'group' => 'auth',
                'label' => 'Minimum Password Length',
                'description' => 'Minimum characters required for passwords',
                'order' => 6,
            ],
            [
                'key' => 'password_require_uppercase',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'auth',
                'label' => 'Require Uppercase',
                'description' => 'Password must contain uppercase letters',
                'order' => 7,
            ],
            [
                'key' => 'password_require_numbers',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'auth',
                'label' => 'Require Numbers',
                'description' => 'Password must contain numbers',
                'order' => 8,
            ],
            [
                'key' => 'password_require_special',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'auth',
                'label' => 'Require Special Characters',
                'description' => 'Password must contain special characters',
                'order' => 9,
            ],
            [
                'key' => 'max_login_attempts',
                'value' => '5',
                'type' => 'integer',
                'group' => 'auth',
                'label' => 'Max Login Attempts',
                'description' => 'Maximum failed login attempts before lockout',
                'order' => 10,
            ],
            [
                'key' => 'lockout_duration',
                'value' => '15',
                'type' => 'integer',
                'group' => 'auth',
                'label' => 'Lockout Duration (minutes)',
                'description' => 'Account lockout duration after max attempts',
                'order' => 11,
            ],

            // Email Settings
            [
                'key' => 'mail_mailer',
                'value' => 'smtp',
                'type' => 'string',
                'group' => 'email',
                'label' => 'Mail Driver',
                'description' => 'Mail driver (smtp, sendmail, mailgun, etc.)',
                'order' => 1,
            ],
            [
                'key' => 'mail_host',
                'value' => 'smtp.mailtrap.io',
                'type' => 'string',
                'group' => 'email',
                'label' => 'SMTP Host',
                'description' => 'SMTP server hostname',
                'order' => 2,
            ],
            [
                'key' => 'mail_port',
                'value' => '2525',
                'type' => 'integer',
                'group' => 'email',
                'label' => 'SMTP Port',
                'description' => 'SMTP server port',
                'order' => 3,
            ],
            [
                'key' => 'mail_encryption',
                'value' => 'tls',
                'type' => 'string',
                'group' => 'email',
                'label' => 'Encryption',
                'description' => 'Encryption type (tls, ssl, or none)',
                'order' => 4,
            ],
            [
                'key' => 'mail_from_address',
                'value' => 'noreply@larakit.com',
                'type' => 'string',
                'group' => 'email',
                'label' => 'From Address',
                'description' => 'Default sender email address',
                'order' => 5,
            ],
            [
                'key' => 'mail_from_name',
                'value' => 'LaraKit',
                'type' => 'string',
                'group' => 'email',
                'label' => 'From Name',
                'description' => 'Default sender name',
                'order' => 6,
            ],

            // Social Media Settings
            [
                'key' => 'facebook_url',
                'value' => '',
                'type' => 'string',
                'group' => 'social',
                'label' => 'Facebook URL',
                'description' => 'Your Facebook page URL',
                'order' => 1,
            ],
            [
                'key' => 'twitter_url',
                'value' => '',
                'type' => 'string',
                'group' => 'social',
                'label' => 'Twitter/X URL',
                'description' => 'Your Twitter/X profile URL',
                'order' => 2,
            ],
            [
                'key' => 'instagram_url',
                'value' => '',
                'type' => 'string',
                'group' => 'social',
                'label' => 'Instagram URL',
                'description' => 'Your Instagram profile URL',
                'order' => 3,
            ],
            [
                'key' => 'linkedin_url',
                'value' => '',
                'type' => 'string',
                'group' => 'social',
                'label' => 'LinkedIn URL',
                'description' => 'Your LinkedIn page URL',
                'order' => 4,
            ],
            [
                'key' => 'youtube_url',
                'value' => '',
                'type' => 'string',
                'group' => 'social',
                'label' => 'YouTube URL',
                'description' => 'Your YouTube channel URL',
                'order' => 5,
            ],
            [
                'key' => 'github_url',
                'value' => '',
                'type' => 'string',
                'group' => 'social',
                'label' => 'GitHub URL',
                'description' => 'Your GitHub profile URL',
                'order' => 6,
            ],

            // Notification Settings
            [
                'key' => 'enable_email_notifications',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'notifications',
                'label' => 'Email Notifications',
                'description' => 'Enable email notifications',
                'order' => 1,
            ],
            [
                'key' => 'enable_push_notifications',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'notifications',
                'label' => 'Push Notifications',
                'description' => 'Enable browser push notifications',
                'order' => 2,
            ],
            [
                'key' => 'enable_sms_notifications',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'notifications',
                'label' => 'SMS Notifications',
                'description' => 'Enable SMS notifications',
                'order' => 3,
            ],
            [
                'key' => 'notify_on_new_user',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'notifications',
                'label' => 'Notify on New User',
                'description' => 'Send notification when new user registers',
                'order' => 4,
            ],

            // Backup & System Settings
            [
                'key' => 'enable_auto_backup',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'backup',
                'label' => 'Enable Auto Backup',
                'description' => 'Automatically backup database',
                'order' => 1,
            ],
            [
                'key' => 'backup_frequency',
                'value' => 'daily',
                'type' => 'string',
                'group' => 'backup',
                'label' => 'Backup Frequency',
                'description' => 'Backup frequency (daily, weekly, monthly)',
                'order' => 2,
            ],
            [
                'key' => 'backup_retention_days',
                'value' => '30',
                'type' => 'integer',
                'group' => 'backup',
                'label' => 'Backup Retention (days)',
                'description' => 'Days to keep backups before deletion',
                'order' => 3,
            ],
            [
                'key' => 'maintenance_mode',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'backup',
                'label' => 'Maintenance Mode',
                'description' => 'Enable maintenance mode',
                'order' => 4,
            ],

            // Developer Options
            [
                'key' => 'app_debug',
                'value' => config('app.debug', false) ? '1' : '0',
                'type' => 'boolean',
                'group' => 'developer',
                'label' => 'Debug Mode',
                'description' => 'Enable debug mode (WARNING: Disable in production)',
                'order' => 1,
            ],
            [
                'key' => 'app_url',
                'value' => config('app.url', 'http://localhost'),
                'type' => 'string',
                'group' => 'developer',
                'label' => 'Application URL',
                'description' => 'Base URL of your application',
                'order' => 2,
            ],
            [
                'key' => 'api_rate_limit',
                'value' => '60',
                'type' => 'integer',
                'group' => 'developer',
                'label' => 'API Rate Limit',
                'description' => 'API requests per minute',
                'order' => 3,
            ],
            [
                'key' => 'enable_api',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'developer',
                'label' => 'Enable API',
                'description' => 'Enable API endpoints',
                'order' => 4,
            ],
            [
                'key' => 'enable_webhooks',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'developer',
                'label' => 'Enable Webhooks',
                'description' => 'Enable webhook functionality',
                'order' => 5,
            ],
            [
                'key' => 'enable_analytics',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'developer',
                'label' => 'Enable Analytics',
                'description' => 'Enable analytics feature',
                'order' => 6,
            ],
            [
                'key' => 'enable_chat',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'developer',
                'label' => 'Enable Chat',
                'description' => 'Enable chat feature',
                'order' => 7,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }

        $this->command->info('Settings seeded successfully!');
    }
}
