@extends('layouts.backend.master')







































































@endsection</div>    </div>        </form>            </div>                </a>                    <i class="fas fa-times"></i> Cancel                <a href="{{ route('modules.show', [$project, $module]) }}" style="padding: 10px 24px; background: #6b7280; color: white; text-decoration: none; border-radius: 8px; font-weight: 600;">                </button>                    <i class="fas fa-save"></i> Update Module                <button type="submit" style="padding: 10px 24px; background: #16a34a; color: white; border: none; border-radius: 8px; font-weight: 600; cursor: pointer;">            <div style="display: flex; gap: 12px; padding-top: 20px; border-top: 1px solid #e5e7eb;">            </div>                @enderror                    <p style="color: #dc2626; font-size: 0.875rem; margin-top: 4px;">{{ $message }}</p>                @error('status')                </select>                    <option value="inactive" {{ old('status', $module->status) == 'inactive' ? 'selected' : '' }}>Inactive</option>                    <option value="active" {{ old('status', $module->status) == 'active' ? 'selected' : '' }}>Active</option>                    style="width: 100%; padding: 10px; border: 1px solid #d1d5db; border-radius: 6px; font-size: 1rem;">                <select name="status" required                 <label style="display: block; font-weight: 600; color: #374151; margin-bottom: 8px;">Status *</label>            <div style="margin-bottom: 20px;">            </div>                @enderror                    <p style="color: #dc2626; font-size: 0.875rem; margin-top: 4px;">{{ $message }}</p>                @error('order')                <p style="color: #6b7280; font-size: 0.875rem; margin-top: 4px;">Determines the display order of modules</p>                    placeholder="Enter order number">                    style="width: 100%; padding: 10px; border: 1px solid #d1d5db; border-radius: 6px; font-size: 1rem;"                 <input type="number" name="order" value="{{ old('order', $module->order) }}" required min="0"                <label style="display: block; font-weight: 600; color: #374151; margin-bottom: 8px;">Order *</label>            <div style="margin-bottom: 20px;">            </div>                @enderror                    <p style="color: #dc2626; font-size: 0.875rem; margin-top: 4px;">{{ $message }}</p>                @error('description')                    placeholder="Enter module description (optional)">{{ old('description', $module->description) }}</textarea>                    style="width: 100%; padding: 10px; border: 1px solid #d1d5db; border-radius: 6px; font-size: 1rem;"                 <textarea name="description" rows="4"                 <label style="display: block; font-weight: 600; color: #374151; margin-bottom: 8px;">Description</label>            <div style="margin-bottom: 20px;">            </div>                @enderror                    <p style="color: #dc2626; font-size: 0.875rem; margin-top: 4px;">{{ $message }}</p>                @error('name')                    placeholder="Enter module name">                    style="width: 100%; padding: 10px; border: 1px solid #d1d5db; border-radius: 6px; font-size: 1rem;"                 <input type="text" name="name" value="{{ old('name', $module->name) }}" required                 <label style="display: block; font-weight: 600; color: #374151; margin-bottom: 8px;">Module Name *</label>            <div style="margin-bottom: 20px;">            @method('PUT')            @csrf        <form action="{{ route('modules.update', [$project, $module]) }}" method="POST">    <div style="background: white; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); border: 1px solid #e5e7eb; padding: 24px; max-width: 800px;">    </div>        <p style="color: #6b7280;">Update module details for {{ $project->name }}</p>        <h1 style="font-size: 2rem; font-weight: bold; color: #1f2937; margin-bottom: 8px;">Edit Module</h1>    <div style="margin-bottom: 24px;"><div style="padding: 24px;">@section('content')@section('title', 'Edit Module')
