@extends('layouts.backend.master')


































































































@endsection</div>    @endif    </div>        </a>            <i class="fas fa-plus"></i> Create Module        <a href="{{ route('modules.create', $project) }}" style="display: inline-block; margin-top: 16px; padding: 10px 20px; background: #16a34a; color: white; text-decoration: none; border-radius: 8px; font-weight: 600;">        <p style="margin-top: 8px; color: #9ca3af;">Create your first module to organize test cases</p>        <p style="font-size: 1.125rem; margin: 0; color: #6b7280;">No modules yet</p>        <i class="fas fa-cube" style="font-size: 3rem; margin-bottom: 16px; opacity: 0.3; color: #6b7280;"></i>    <div style="background: white; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); border: 1px solid #e5e7eb; padding: 48px; text-align: center;">    @else    </div>        </table>            </tbody>                @endforeach                </tr>                    </td>                        </div>                            </form>                                </button>                                    <i class="fas fa-trash"></i>                                <button type="submit" style="padding: 6px 12px; background: #dc2626; color: white; border: none; border-radius: 6px; cursor: pointer; font-size: 0.875rem;">                                @method('DELETE')                                @csrf                            <form action="{{ route('modules.destroy', [$project, $module]) }}" method="POST" style="display: inline;" onsubmit="return confirm('Are you sure? This will delete all test cases in this module.');">                            </a>                                <i class="fas fa-edit"></i>                            <a href="{{ route('modules.edit', [$project, $module]) }}" style="padding: 6px 12px; background: #f59e0b; color: white; text-decoration: none; border-radius: 6px; font-size: 0.875rem;">                            </a>                                <i class="fas fa-eye"></i>                            <a href="{{ route('modules.show', [$project, $module]) }}" style="padding: 6px 12px; background: #2563eb; color: white; text-decoration: none; border-radius: 6px; font-size: 0.875rem;">                        <div style="display: flex; gap: 8px; justify-content: flex-end;">                    <td style="padding: 12px 16px; text-align: right;">                    </td>                        </span>                            {{ ucfirst($module->status) }}                        <span style="padding: 4px 12px; border-radius: 12px; font-size: 0.75rem; font-weight: 600; background: {{ $module->status === 'active' ? '#dcfce7' : '#fee2e2' }}; color: {{ $module->status === 'active' ? '#166534' : '#b91c1c' }};">                    <td style="padding: 12px 16px;">                    </td>                        </span>                            {{ $module->testCases->count() }}                        <span style="padding: 4px 8px; background: #f3f4f6; color: #374151; border-radius: 4px; font-weight: 600;">                    <td style="padding: 12px 16px;">                    </td>                        {{ Str::limit($module->description, 50) ?? 'No description' }}                    <td style="padding: 12px 16px; color: #6b7280;">                    </td>                        </a>                            {{ $module->name }}                        <a href="{{ route('modules.show', [$project, $module]) }}" style="color: #2563eb; text-decoration: none; font-weight: 500;">                    <td style="padding: 12px 16px;">                    </td>                        </span>                            {{ $module->order }}                        <span style="padding: 4px 8px; background: #dbeafe; color: #1e40af; border-radius: 4px; font-weight: 600;">                    <td style="padding: 12px 16px;">                <tr style="border-bottom: 1px solid #e5e7eb;">                @foreach($modules as $module)            <tbody>            </thead>                </tr>                    <th style="padding: 12px 16px; text-align: right; font-weight: 600; color: #374151;">Actions</th>                    <th style="padding: 12px 16px; text-align: left; font-weight: 600; color: #374151;">Status</th>                    <th style="padding: 12px 16px; text-align: left; font-weight: 600; color: #374151;">Test Cases</th>                    <th style="padding: 12px 16px; text-align: left; font-weight: 600; color: #374151;">Description</th>                    <th style="padding: 12px 16px; text-align: left; font-weight: 600; color: #374151;">Name</th>                    <th style="padding: 12px 16px; text-align: left; font-weight: 600; color: #374151;">Order</th>                <tr>            <thead style="background: #f9fafb; border-bottom: 1px solid #e5e7eb;">        <table style="width: 100%; border-collapse: collapse;">        </div>            <h2 style="font-size: 1.25rem; font-weight: 600; color: #1f2937; margin: 0;">All Modules</h2>        <div style="padding: 16px 24px; border-bottom: 1px solid #e5e7eb;">    <div style="background: white; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); border: 1px solid #e5e7eb; overflow: hidden;">    @if($modules->count() > 0)    </div>        </div>            </a>                <i class="fas fa-arrow-left"></i> Back to Project            <a href="{{ route('projects.show', $project) }}" style="padding: 10px 20px; background: #6b7280; color: white; text-decoration: none; border-radius: 8px; font-weight: 600;">            </a>                <i class="fas fa-plus"></i> Add Module            <a href="{{ route('modules.create', $project) }}" style="padding: 10px 20px; background: #16a34a; color: white; text-decoration: none; border-radius: 8px; font-weight: 600;">        <div style="display: flex; gap: 12px;">        </div>            <p style="color: #6b7280;">Manage modules for this project</p>            <h1 style="font-size: 2rem; font-weight: bold; color: #1f2937; margin-bottom: 8px;">Modules - {{ $project->name }}</h1>        <div>    <div style="margin-bottom: 24px; display: flex; justify-content: space-between; align-items: center;"><div style="padding: 24px;">@section('content')@section('title', 'Modules - ' . $project->name)
